services:
  database:
    image: postgres:13.22-trixie
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z-cpuv1
    env_file:
      - .env
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_CONSOLE_ADDRESS=:9001
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - miniodata:/data
    command: server /data

volumes:
  postgres-data:
  miniodata: