spring:
  application:
   name: cloud_storage
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/cloud-storage
    password: 123
    username: postgres
  data:
    jdbc:
      dialect: postgresql
  liquibase:
    change-log: db/changelog/changelog-master.xml
    analytics-enabled: true
