spring:
  application:
   name: cloud_storage
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/cloud-storage
    password: 123
    username: postgres
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  liquibase:
    change-log: db/changelog/changelog-master.xml
    enabled: true

minio:
  endpoint: "http://localhost:9000"
  username: admin
  password: 12345678
  users-bucket: "user-files"

logging:
  level:
    org.springframework.security.authentication.dao: DEBUG